### ISSUE TITLE
Data source

### ISSUE THREAD

**Issue by yqsong** [HKUST-KnowComp/Motif-based-PageRank#1]
Hi Huan and Xiaogang,

Can you include where the data are originally from and cite the URLs and/or papers?

Thanks,
Yangqiu

**Comment by hzhaoaf** [comment]
@yqsong yes, it's updated in ReadMe file.

**Comment by SharonGao199** [comment]
Hello Huan and Xiaogang and thank you !
But I have a confusion: where did the "average_helpfulness_Epinion.txt" play its role in the corresponding code?
Thank you again!
